Properly format os.version property
AdoptOpenJDK/openjdk-jdk8u-backup pull request #6
Opened 2017-09-21 05:09 UTC by gblues

=== ISSUE
fix for issue #5 
=== DETAILS
AIX is a weird beast, where the OS release and version are stored in
separate parts of the `utsname` structure.

By default, the JVM only grabs one of the two fields. This is what
causes `os.version` to return `2` on AIX 7.2.

I've added a function that allocates a string and writes the formatted
version into it. Since AIX' `strdup()` implementation performs a
`malloc()`, this effectively preserves the existing behavior.
=== TESTING
Unfortunately, I don't have an AIX system to do any kind of a test build
on.

Potential pitfalls:

* The method's been added to the wrong file.
* The AIX build has neither `__linux__` or `_ALLBSD_SOURCE` defined,
  and thus compilation fails due to missing `stdio.h` include
* dumb human error

2017-09-21 08:09 UTC, karianna commented
@gblues - Have you reported this bug in the upstream OpenJDK 8u project?  I think we should test your fix here and then report the bug along with this associated patch in OpenJDK proper.  Only if they refuse to accept the patch should we then apply it here (and in 9 etc).

2017-09-21 08:12 UTC, karianna requested changes
A few Q's and comments

2017-09-21 08:12 UTC, karianna commented on jdk/src/solaris/native/java/lang/java_props_md.c
> +char *
Not suer why that char * is there?

2017-09-21 08:12 UTC, karianna commented on jdk/src/solaris/native/java/lang/java_props_md.c
> +GetAixVersionString(char *version, char *release)
start with Camel case

2017-09-21 08:12 UTC, karianna commented on jdk/src/solaris/native/java/lang/java_props_md.c
> +    // the 2 accounts for null-terminator and the '.' between release and version strings
Can you edit the comment with an example of what this looks like?

2017-09-21 08:12 UTC, karianna commented on jdk/src/solaris/native/java/lang/java_props_md.c
> +    result = (char *)malloc(bytesNeeded);
We've malloc'd, do we need to release anything once we're done?

2017-09-21 15:37 UTC, gblues commented on jdk/src/solaris/native/java/lang/java_props_md.c
> +    result = (char *)malloc(bytesNeeded);
No. `GetAixVersionString` follows the same semantics as `strdup`, in that it is the caller's responsibility to free the memory. In this way it is drop-in compatible with the previous code which simply `strdup()`ed the version field out of the uname structure.

2017-09-21 15:50 UTC, gblues commented on jdk/src/solaris/native/java/lang/java_props_md.c
> +    // the 2 accounts for null-terminator and the '.' between release and version strings
No problem. I've just pushed up an edit (and caught a couple of my own dumb errors too).

2017-09-21 16:24 UTC, gblues commented
@karianna it looks like it's already been resolved in OpenJDK 9 (https://bugs.openjdk.java.net/browse/JDK-8132374).

I don't have JIRA access to directly request a backport, but I've e-mailed the jdk8u lead (Sean Coffey).

2017-09-22 11:14 UTC, karianna commented on jdk/src/solaris/native/java/lang/java_props_md.c
> +    result = (char *)malloc(bytesNeeded);
Perfect, thanks

2017-09-22 11:16 UTC, karianna commented
OK, let's see what Sean says.  This patch is now good, but I'd prefer (no offense!) just to have the OpenJDK 9 one backported (consistency).

2017-09-22 11:16 UTC, karianna approved these changes

2017-09-22 15:22 UTC, gblues commented
Haha, no offense taken!

Latest news from upstream: Sean has reached out to Volker Simonis, who's just put a RFA out to jdk8u-dev.

2017-09-22 20:36 UTC, gblues commented
@karianna Upstream has backported the JDK9 fix: https://bugs.openjdk.java.net/browse/JDK-8187859. Closing.

2017-09-22 20:36 UTC, closed without merging

2017-09-25 08:47 UTC, karianna commented
@gblues Great work!